parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    produit_pictures_directory: '%kernel.project_dir%/public/uploads/produits'

services:
    # ⬇ Explicitly define the UserChecker service if needed
    App\Security\UserChecker:
        autowire: true
        autoconfigure: true

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
