controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_event_index:
    path: /event
    controller: App\Controller\EventController::index
    methods: [GET]
